if: type != push OR branch = master

services:
  - docker

language: bash

script:
  - docker build -t $IMAGE_NAME .
  - docker build -t heroes-acceptence-tests heroes-acceptence-tests
  - docker images
  - docker run --name ash -d --rm -p 8080:8080 $IMAGE_NAME
  - sleep 30
  - docker run -it --rm --link ash heroes-acceptence-tests --config baseUrl=http://ash:8080

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
