if: type != push OR branch = master

services:
  - docker

language: java
jdk:
  - openjdk11

script:
  - mvn $MAVEN_CLI_OPTS package jib:dockerBuild
  - docker build -t heroes-acceptence-tests heroes-acceptence-tests
  - docker images
  - docker run --name ash -d --rm -p 8080:8080 porscheinformatik/angular-spring-heroes
  - sleep 30
  - docker run -it --rm --link ash heroes-acceptence-tests --config baseUrl=http://ash:8080

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
