apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  postgres-user: {{ default "sampledb" .Values.postgresUser | b64enc | quote }}
  {{- if .Values.postgresPassword }}
  postgres-password:  {{ .Values.postgresPassword | b64enc | quote }}
  {{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
