{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "angular-spring-heroes.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    deployment: {{ template "angular-spring-heroes.name" . }}
    chart: {{ template "angular-spring-heroes.chart" . }}
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: "{{ template "angular-spring-heroes.fullname" . }}-tls"
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ template "angular-spring-heroes.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
