{{- if .Values.route.enabled -}}
{{- $fullName := include "angular-spring-heroes.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    chart: {{ template "angular-spring-heroes.chart" . }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- else if .Values.route.basename }}
  host: "{{ $fullName }}.{{ .Values.route.basename }}"
  {{- end }}
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ $fullName }}
{{- end }}
